spring:
  datasource:
    url: jdbc:mysql://localhost:3306/obsr_crud?useSSL=false&serverTimezone=UTC&nullNamePatternMatchesAll=true
    username: springtest
    password: spring4all
    driver-class-name: com.mysql.cj.jdbc.Driver
    liquibase:
      change-log: classpath:/db/default/scripts.xml
  jpa:
    hibernate:
      ddl-auto: none
